font:
  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_72
    size: 72
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_48
    size: 48
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_42
    size: 42
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_36
    size: 36
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_24
    size: 24
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_20
    size: 20
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_18
    size: 18
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_14
    size: 14
    bpp: 8

  - file: hotplate/Nunito-SemiBold.ttf
    id: nunito_12
    size: 12
    bpp: 8
