substitutions:
  led_0: GPIO21
  led_1: GPIO47
  led_2: GPIO48
  led_3: GPIO17
  led_4: GPIO18
  vcc_sens: GPIO1
  board_led: GPIO2

  cs_lcd: GPIO38
  rst_lcd: GPIO7
  dc_lcd: GPIO3
  mosi_lcd: GPIO39
  mclk_lcd: GPIO40
  bl_lcd: GPIO42
  miso_lcd: GPIO41
  clk_touch: GPIO12
  rst_touch: GPIO10
  sda_touch: GPIO11
  cs_card: GPIO15

  ext_scl: GPIO14
  ext_sda: GPIO13
  
external_components:
  - source: github://kodi1/esphome_fuzzy
    components: mlx90640
    refresh: 0s

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

packages:
  wifi: !include common/wifi.yaml
  sensors: !include termal_cam/sensors.yaml
  hardware: !include termal_cam/hardware.yaml
  lvgl: !include termal_cam/lvgl.yaml
  ota: !include termal_cam/ota.yaml

logger:
  level: VERBOSE
  initial_level: WARN
  logs:
    touch: DEBUG
    main: DEBUG

esphome:
  name: thermal-cam
  # name_add_mac_suffix: true
  comment: "thermal cam board"
  includes:
    - <cstdint>
    - "termal_cam/thermal_cam.h"

  on_boot:
    - priority: 0
      then:
        - lvgl.page.show: boot_page
        - delay: 3s
        - light.turn_on:
            id: back_light
            brightness: 50%
            
interval:
  - interval: 1s
    then:
      <<: !include termal_cam/ui_update.yaml
